services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LD\LanguageDetection\:
    resource: '../Classes/*'

  LD\LanguageDetection\Check\SiteListener:
    tags:
      - name: event.listener
        identifier: 'languageDetectionSite'
        event: LD\LanguageDetection\Event\CheckLanguageDetection

  LD\LanguageDetection\Check\EnableListener:
    tags:
      - name: event.listener
        after: 'languageDetectionSite'
        identifier: 'languageDetectionEnable'
        event: LD\LanguageDetection\Event\CheckLanguageDetection

  LD\LanguageDetection\Check\BotListener:
    tags:
      - name: event.listener
        after: 'languageDetectionEnable'
        identifier: 'languageDetectionBot'
        event: LD\LanguageDetection\Event\CheckLanguageDetection

  LD\LanguageDetection\Check\FromCurrentPageListener:
    tags:
      - name: event.listener
        after: 'languageDetectionEnable'
        identifier: 'languageDetectionFromCurrentPage'
        event: LD\LanguageDetection\Event\CheckLanguageDetection

  LD\LanguageDetection\Check\WorkspacePreviewListener:
    tags:
      - name: event.listener
        after: 'languageDetectionEnable'
        identifier: 'languageDetectionWorkspacePreview'
        event: LD\LanguageDetection\Event\CheckLanguageDetection

  LD\LanguageDetection\Check\PathListener:
    tags:
      - name: event.listener
        after: 'languageDetectionEnable'
        identifier: 'languageDetectionPath'
        event: LD\LanguageDetection\Event\CheckLanguageDetection

  LD\LanguageDetection\Check\BackendUserListener:
    tags:
      - name: event.listener
        after: 'languageDetectionEnable'
        identifier: 'languageDetectionBackendUser'
        event: LD\LanguageDetection\Event\CheckLanguageDetection

  LD\LanguageDetection\Negotiation\DefaultNegotiation:
    tags:
      - name: event.listener
        identifier: 'defaultNegotiation'
        event: LD\LanguageDetection\Event\NegotiateSiteLanguage

  LD\LanguageDetection\Negotiation\FallbackNegotiation:
    tags:
      - name: event.listener
        identifier: 'fallbackNegotiation'
        after: 'defaultNegotiation'
        event: LD\LanguageDetection\Event\NegotiateSiteLanguage

  LD\LanguageDetection\Detect\BrowserLanguage:
    tags:
      - name: event.listener
        identifier: 'browserLanguage'
        event: LD\LanguageDetection\Event\DetectUserLanguages

  LD\LanguageDetection\Detect\IpLanguage:
    tags:
      - name: event.listener
        identifier: 'ipLanguage'
        after: 'browserLanguage'
        event: LD\LanguageDetection\Event\DetectUserLanguages

  LD\LanguageDetection\Response\DefaultResponse:
    tags:
      - name: event.listener
        identifier: 'defaultResponse'
        event: LD\LanguageDetection\Event\BuildResponse
