services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Lochmueller\LanguageDetection\:
    resource: '../Classes/*'

  Lochmueller\LanguageDetection\Check\EnableCheck:
    tags:
      - name: event.listener
        identifier: 'languageDetectionEnableCheck'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetectionEvent

  Lochmueller\LanguageDetection\Check\BotAgentCheck:
    tags:
      - name: event.listener
        identifier: 'languageDetectionBotAgentCheck'
        after: 'languageDetectionEnableCheck'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetectionEvent

  Lochmueller\LanguageDetection\Check\FromCurrentPageCheck:
    tags:
      - name: event.listener
        identifier: 'languageDetectionFromCurrentPageCheck'
        after: 'languageDetectionEnableCheck'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetectionEvent

  Lochmueller\LanguageDetection\Check\WorkspacePreviewCheck:
    tags:
      - name: event.listener
        identifier: 'languageDetectionWorkspacePreviewCheck'
        after: 'languageDetectionEnableCheck'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetectionEvent

  Lochmueller\LanguageDetection\Check\PathCheck:
    tags:
      - name: event.listener
        identifier: 'languageDetectionPathCheck'
        after: 'languageDetectionEnableCheck'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetectionEvent

  Lochmueller\LanguageDetection\Check\BackendUserCheck:
    tags:
      - name: event.listener
        identifier: 'languageDetectionBackendUserCheck'
        after: 'languageDetectionEnableCheck'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetectionEvent

  Lochmueller\LanguageDetection\Check\RequestMethodCheck:
    tags:
      - name: event.listener
        identifier: 'languageDetectionRequestMethodCheck'
        after: 'languageDetectionEnableCheck'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetectionEvent

  Lochmueller\LanguageDetection\Negotiation\DefaultNegotiation:
    tags:
      - name: event.listener
        identifier: 'languageDetectionDefaultNegotiation'
        event: Lochmueller\LanguageDetection\Event\NegotiateSiteLanguageEvent

  Lochmueller\LanguageDetection\Negotiation\FallbackNegotiation:
    tags:
      - name: event.listener
        identifier: 'languageDetectionFallbackNegotiation'
        after: 'languageDetectionDefaultNegotiation'
        event: Lochmueller\LanguageDetection\Event\NegotiateSiteLanguageEvent

  Lochmueller\LanguageDetection\Detect\BrowserLanguageDetect:
    tags:
      - name: event.listener
        identifier: 'languageDetectionBrowserLanguageDetect'
        event: Lochmueller\LanguageDetection\Event\DetectUserLanguagesEvent

  Lochmueller\LanguageDetection\Detect\GeoPluginDetect:
    tags:
      - name: event.listener
        identifier: 'languageDetectionGeoPluginDetect'
        after: 'languageDetectionBrowserLanguageDetect'
        event: Lochmueller\LanguageDetection\Event\DetectUserLanguagesEvent

  Lochmueller\LanguageDetection\Detect\MaxMindDetect:
    tags:
      - name: event.listener
        identifier: 'languageDetectionMaxMindDetect'
        after: 'languageDetectionBrowserLanguageDetect'
        event: Lochmueller\LanguageDetection\Event\DetectUserLanguagesEvent

  Lochmueller\LanguageDetection\Response\DefaultResponse:
    tags:
      - name: event.listener
        identifier: 'languageDetectionDefaultResponse'
        event: Lochmueller\LanguageDetection\Event\BuildResponseEvent
