services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Lochmueller\LanguageDetection\:
    resource: '../Classes/*'

  Lochmueller\LanguageDetection\Check\EnableCheck:
    tags:
      - name: event.listener
        after: 'languageDetectionSite'
        identifier: 'languageDetectionEnable'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetection

  Lochmueller\LanguageDetection\Check\BotAgentCheck:
    tags:
      - name: event.listener
        after: 'languageDetectionEnable'
        identifier: 'languageDetectionBot'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetection

  Lochmueller\LanguageDetection\Check\FromCurrentPageCheck:
    tags:
      - name: event.listener
        after: 'languageDetectionEnable'
        identifier: 'languageDetectionFromCurrentPage'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetection

  Lochmueller\LanguageDetection\Check\WorkspacePreviewCheck:
    tags:
      - name: event.listener
        after: 'languageDetectionEnable'
        identifier: 'languageDetectionWorkspacePreview'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetection

  Lochmueller\LanguageDetection\Check\PathCheck:
    tags:
      - name: event.listener
        after: 'languageDetectionEnable'
        identifier: 'languageDetectionPath'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetection

  Lochmueller\LanguageDetection\Check\BackendUserCheck:
    tags:
      - name: event.listener
        after: 'languageDetectionEnable'
        identifier: 'languageDetectionBackendUser'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetection

  Lochmueller\LanguageDetection\Check\RequestMethodCheck:
    tags:
      - name: event.listener
        after: 'languageDetectionEnable'
        identifier: 'languageDetectionRequestMethod'
        event: Lochmueller\LanguageDetection\Event\CheckLanguageDetection

  Lochmueller\LanguageDetection\Negotiation\DefaultNegotiation:
    tags:
      - name: event.listener
        identifier: 'defaultNegotiation'
        event: Lochmueller\LanguageDetection\Event\NegotiateSiteLanguage

  Lochmueller\LanguageDetection\Negotiation\FallbackNegotiation:
    tags:
      - name: event.listener
        identifier: 'fallbackNegotiation'
        after: 'defaultNegotiation'
        event: Lochmueller\LanguageDetection\Event\NegotiateSiteLanguage

  Lochmueller\LanguageDetection\Detect\BrowserLanguage:
    tags:
      - name: event.listener
        identifier: 'browserLanguage'
        event: Lochmueller\LanguageDetection\Event\DetectUserLanguages

  Lochmueller\LanguageDetection\Detect\IpLanguage:
    tags:
      - name: event.listener
        identifier: 'ipLanguage'
        after: 'browserLanguage'
        event: Lochmueller\LanguageDetection\Event\DetectUserLanguages

  Lochmueller\LanguageDetection\Detect\MaxMindDetect:
    tags:
      - name: event.listener
        identifier: 'maxMindDetect'
        after: 'ipLanguage'
        event: Lochmueller\LanguageDetection\Event\DetectUserLanguages

  Lochmueller\LanguageDetection\Response\DefaultResponse:
    tags:
      - name: event.listener
        identifier: 'defaultResponse'
        event: Lochmueller\LanguageDetection\Event\BuildResponse
