services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LD\LanguageDetection\:
    resource: '../Classes/*'

  LD\LanguageDetection\Listener\EnableListener:
    tags:
      - name: event.listener
        identifier: 'languageDetectionEnable'
        event: LD\LanguageDetection\Event\HandleLanguageDetection

  LD\LanguageDetection\Listener\FromCurrentPageListener:
    tags:
      - name: event.listener
        identifier: 'languageDetectionFromCurrentPage'
        event: LD\LanguageDetection\Event\HandleLanguageDetection

  LD\LanguageDetection\Listener\WorkspacePreviewListener:
    tags:
      - name: event.listener
        identifier: 'languageDetectionWorkspacePreview'
        event: LD\LanguageDetection\Event\HandleLanguageDetection

  LD\LanguageDetection\Listener\PathListener:
    tags:
      - name: event.listener
        identifier: 'languageDetectionPath'
        event: LD\LanguageDetection\Event\HandleLanguageDetection

  LD\LanguageDetection\Listener\BackendUserListener:
    tags:
      - name: event.listener
        identifier: 'languageDetectionBackendUser'
        event: LD\LanguageDetection\Event\HandleLanguageDetection

  LD\LanguageDetection\Negotiation\DefaultNegotiation:
    tags:
      - name: event.listener
        identifier: 'defaultNegotiation'
        event: LD\LanguageDetection\Event\NegotiateSiteLanguage
